### ISSUE TITLE
Initialization runs too soon

### ISSUE THREAD

**Issue by wagenet** [dockyard/qunit-notifications#12]
Due to changes in the most recent versions of QUnit (1.16.0+) (or possibly ember-cli initialization) the following initialization code is run prematurely: https://github.com/dockyard/qunit-notifications/blob/master/index.js#L46. I was able to reproduce this issue by updating my qunit in the most recent version of ember-cli.

**Comment by wagenet** [comment]
I hope to look into this more next week if no one else has looked at it.

**Comment by bcardarella** [comment]
I believe #7 fixes this. I haven't had a chance yet to confirm

**Comment by wagenet** [comment]
Looks like it will. Should have looked first.
