### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by amercier** [dockyard/qunit-notifications#14]
We should add unit tests with window.Notification being spied using [Sinon.JS](http://sinonjs.org/), or an equivalent.

**Comment by bcardarella** [comment]
:+1: I was not sure how best to test a test suite

**Comment by amercier** [comment]
QUnit is [tested by itself](https://github.com/jquery/qunit/tree/master/test), for instance.

**Comment by amercier** [comment]
I'll work on that. I'm pretty confident that's feasible.
