### ISSUE TITLE
Toolbar not ready, making tests fail

### ISSUE THREAD

**Issue by mauricioac** [dockyard/qunit-notifications#15]
Using ember-cli on a project, opening the tests tab, tests fail because Qunit Notifications fail to add itself to Qunit toolbar.

Tried making a PR, but got closed. I guess it's on your hands now.

**Comment by bcardarella** [comment]
@mauricioac can you ensure you're using QUnit 1.16.

Unfortunately Bower sucks and we can't ensure version locking between dependencies.

@amercier maybe we can add feature detection for both versions?

**Comment by amercier** [comment]
Caused by both:
- ember-cli not using QUnit v1.16 (latest)
- qunit-notifications incompatibility issue with QUnit < v1.16

I will patch this soon.

**Comment by mauricioac** [comment]
Yes, we're using QUnit 1.16.

**Comment by amercier** [comment]
OK. Will look into this tomorrow.

**Comment by stefanpenner** [comment]
yes this doesn't work

**Comment by stefanpenner** [comment]
bower troll, latest works fine.

**Comment by stefanpenner** [comment]
this can be closed

**Comment by mauricioac** [comment]
:+1: tested latest version, indeed works

**Comment by jme783** [comment]
What if I'm using `ember-qunit-notifications`? Is there a fix for that?
