### ISSUE TITLE
Toolbar not ready, making tests fail with QUnit < 1.16

### ISSUE THREAD

**Issue by amercier** [dockyard/qunit-notifications#17]
Tests fail because QUnit Notifications fail to add itself to QUnit toolbar.

- OK with latest QUnit (v1.16)
- NOK with QUnit v1.15 (and probably below as well)

Thanks @mauricioac for reporting this.
Separated this issue from #4 and #15 for clearer tracking.

**Comment by mfeckie** [comment]
FYI, this is where the problem go introduced

https://github.com/jquery/qunit/commit/d86d6c38991a82e2c534eacc03dd10eac1ca1e69

Basically QUnit.url has been made a private function

**Comment by rwjblue** [comment]
Just confirming @mfeckie's assessment. qunit-notifications does not work on QUnit 1.1.17 (and therefore ember-cli which defaults to 1.1.17).

@amercier - Any idea's on a way forward here?

**Comment by bcardarella** [comment]
Well this sucks. Awesome of QUnit team to break public API like that

**Comment by amercier** [comment]
@mfeckie @rwjblue @bcardarella I agree, this sucks and we need to fix it ASAP.

**Comment by bcardarella** [comment]
Left a comment https://github.com/jquery/qunit/commit/d86d6c38991a82e2c534eacc03dd10eac1ca1e69#commitcomment-9471316

**Comment by rwjblue** [comment]
I'm looking into a potential fix...

**Comment by mauricioac** [comment]
Thanks guys for the attention on this :+1:

**Comment by bcardarella** [comment]
@rwjblue technically you could just hack the DOM. `QUnit.url` was a nice way to easily add and setup the events.

At the end of the day it might be too much of a pain in the ass, we should consider removing `ember-notifications` from `ember-cli` default.

**Comment by amercier** [comment]
Reopening since #19 fixed incompatibility with QUnit v1.17.0, not QUnit < v1.16.0

**Comment by amercier** [comment]
QUnit Notifcations tests suite won't even load because it needs newest QUnit APIs (`assert.async`, module `beforeEach`).

However, manual testing worked fine using:
1. [stubs](../blob/master/tests/stubs/) from latest version of QUnit Notifications
2. `"qunit": "1.15.0",` in `bower.json`

Closing for now. Feel free to reopen if the issue occurs in your case (and provide your QUnit version, please).
