### ISSUE TITLE
Release as an NPM module

### ISSUE THREAD

**Issue by trentmwillis** [DockYard/qunit-notifications#25]
The Ember community is trying to standardize around a single package manager (NPM) and in order to port `ember-qunit-notifications`, this package will also need to be available as an NPM package.

From my explorations, no heavy work is needed here. Just need to add a version to the `package.json` and release. The current repo structure is sufficient.

cc @stefanpenner

**Comment by bcardarella** [comment]
Done

**Comment by trentmwillis** [comment]
Many thanks!

**Comment by bcardarella** [comment]
Kill bower with :fire: please

**Comment by stefanpenner** [comment]
getting close, thanks!
