### ISSUE TITLE
0.0.6 bower version published?

### ISSUE THREAD

**Issue by williamsbdev** [DockYard/qunit-notifications#27]
I am unable to do `bower install qunit-notifications@0.0.6`. This is a dependency of the `ember-qunit-notifications` where it is attempting to do a `~0.0.6`. We also checked versions `0.0.7`, `0.0.8`, and `0.0.9` but none of these seem to be published either. Can you provide some guidance on how we could fix this?

Thanks!

**Comment by bcardarella** [comment]
It has been moved over to npm: https://www.npmjs.com/package/qunit-notifications

**Comment by williamsbdev** [comment]
@bcardarella - Thank you very much for the quick response. Just so I understand correctly, all we need to do is completely remove the `ember-qunit-notifications` from our bower.json and replace it with `qunit-notifications` in our package.json?

**Comment by bcardarella** [comment]
What version of ember-cli are you using?

re: bower

Bower should be pulling from the git tags in the repo, those haven't changed. I don't recall ever removing qunit-notifications from Bower, if it isn't being tracked I'm not sure why

**Comment by williamsbdev** [comment]
We are using ember-cli@2.6.2 and bower@1.7.7.

I agree. We see that the tags are still applied on the git repo so we were not sure why it was unable to pull the dependency.

@bcardarella - Thanks again for all the help.

**Comment by bcardarella** [comment]
If you've been upgrading an existing app you may need to realign the bower and npm deps. I believe for that version of ember-cli qunit-notifications is expected to be on npm: https://github.com/ember-cli/ember-cli-qunit/blob/master/package.json#L36

and ember-qunit-notifications is expected to be on bower: https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json#L6

**Comment by bcardarella** [comment]
That being said, I don't know why ember-qunit-notfications is not on npm

/cc @trentmwillis

**Comment by williamsbdev** [comment]
@bcardarella - I see. We must have missed that during our upgrade of ember-cli from 2.5.0 (I believe) to 2.6.2.

ember-qunit-notifications still exists on bower. The issue is that it depends on qunit-notifications with ~0.0.6 and bower cannot find any version to match this so we error. I think we should be able to get past this issue now. Thanks again for all your help with this!

**Comment by trentmwillis** [comment]
> I don't know why ember-qunit-notfications is not on npm

Per a conversation that I can't seem to find (might have happened on Slack), we decided to cut out the need for `ember-qunit-notifications`. You should only need `ember-cli-qunit` now (ref: https://github.com/ember-cli/ember-cli-qunit/pull/119).

That said, I never got around to updating the ember-cli blueprints to remove `ember-qunit-notifications`. Will do that now.
